task: detect
mode: train
model: null
data: null
epochs: 72
patience: 20
batch: 16
imgsz: 320
save: true
save_period: -1
cache: false
device: null
workers: 4
project: null
name: null
exist_ok: false
pretrained: false
optimizer: AdamW
verbose: true
seed: 0
deterministic: true
single_cls: false
rect: false
cos_lr: true
close_mosaic: 10
resume: false
amp: true
fraction: 1.0
freeze: None
overlap_mask: true
mask_ratio: 4
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
show: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
vid_stride: 1
stream_buffer: false
line_width: null
augment: false
agnostic_nms: false
classes: null
retina_masks: false
boxes: true
lr0: 0.0015
lrf: 0.01
momentum: 0.9
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.0015
box: 7.5
cls: 0.5
dfl: 1.5
spike_balance: 0.1
spike_balance_schedule:
  enable: false
  type: piecewise
  milestones: []
  values: []
label_smoothing: 0.0
nbs: 64
hsv_h: 0
hsv_s: 0
hsv_v: 0
degrees: 0.0
translate: 0.1
scale: 0.3
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0
mixup: 0.0
copy_paste: 0.0
event_image_size:
- 240
- 304
event_micro_slice: 6
event_representation: fused_count_surface
event_tau: 50000.0
event_time_reverse: true
event_column_order:
- 0
- 1
- 3
- 2
event_no_letterbox_pad: false
event_train_shape: null
event_train_shuffle: false
cuda_visible_devices: null
cfg: null
